### Test the categories
### Get categories
GET http://localhost:3001/categories

### Test creating a category
POST http://localhost:3001/categories
Content-Type: application/json

{
    "Type": "Sport implements (golf clubs)"
    
}
### Test the PUT which should change a prod. category
PUT http://localhost:3001/categories/5f30cb227602413cd9646895
Content-Type: application/json

{
    "Type": "Sport supplies (club handle padding)",
    "Message": "Changed from 'Sport implements'"
}

### Test the Delete which should remove a category via id ref
DELETE http://localhost:3001/categories/5f30c71858bf293b16136224
